plugins {
    id "com.android.application"
}

android {
    namespace "io.github.silverpoetry.hyperos.aodbridge"
    compileSdk 36

    defaultConfig {
        applicationId "io.github.silverpoetry.hyperos.aodbridge"
        minSdk 33
        targetSdk 36
        versionCode 12
        versionName "1.9-core"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            merges += ["META-INF/xposed/*"]
        }
    }
}

dependencies {
    compileOnly "io.github.libxposed:api:101.0.1"
}
